/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ModeloTabelaSeries;
import modeloConection.ConexaoBD;

/**
 *
 * @author Mayke
 */
public class RelatorioSeries extends javax.swing.JFrame {
    ConexaoBD conex = new ConexaoBD();

   
    public RelatorioSeries() {
        initComponents();
        preencherTabela("select *from \"Series\" order by nome_serie");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorioSeries = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRelatorioSeries.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableRelatorioSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableRelatorioSeries);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencherTabela(String Sql){
    ArrayList dadosSeries = new ArrayList();
    String[] colunasSeries = new String []{"Nome","Genero","Sinopse","Classificacao",};
    conex.conexao();
    conex.executaSql(Sql);
    
    try{
        conex.rs.first();
            do{
             dadosSeries.add(new Object[]{conex.rs.getString("nome_series"),conex.rs.getString("genero_series"),conex.rs.getString("sinopse_series"),conex.rs.getString("classificacao_series")});            
            }while(conex.rs.next());
            
     }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList"+ex);
     }
     ModeloTabelaSeries modelo = new ModeloTabelaSeries(dadosSeries, colunasSeries);
        
        jTableRelatorioSeries.setModel(modelo);
        jTableRelatorioSeries.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableRelatorioSeries.getColumnModel().getColumn(0).setResizable(false);
        jTableRelatorioSeries.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableRelatorioSeries.getColumnModel().getColumn(1).setResizable(false);
        jTableRelatorioSeries.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTableRelatorioSeries.getColumnModel().getColumn(2).setResizable(false);
        jTableRelatorioSeries.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableRelatorioSeries.getColumnModel().getColumn(3).setResizable(false);
        jTableRelatorioSeries.getTableHeader().setReorderingAllowed(false);
        jTableRelatorioSeries.setAutoResizeMode(jTableRelatorioSeries.AUTO_RESIZE_OFF);
        jTableRelatorioSeries.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
     }
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioSeries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorioSeries;
    // End of variables declaration//GEN-END:variables

    
   

    
}
